### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jakeprem**
Changed deploy.deploy_method to deploy.method.

In version 1.0 deploy_method doesn't work but deploy.method does.

### CODE REVIEW

**Comment by Ross-Hunter** [comment]
:+1: 

Just wasted a bit of time on this typo.

**Comment by brianlittmann** [comment]
Same. The generic error message isn't initially helpful:
```
ERROR: You need to activate the deploy extension in config.rb.
```
But the examples it includes do use the 1.0 syntax of `deploy.method`.

**Comment by MichaelDowse** [comment]
:+1:  Also wasted time on this

**Comment by azangru** [comment]
Yes please! I was also struggling with this error.

**Comment by mdmartinez** [comment]
Yes, please merge this soon. Wasted some time on this.

**Comment by tarky** [comment]
:+1: 
Please merge this as soon as possible. I wasted 2 hours.
I think new commers couldn't solve this easily.

**Comment by cllns** [comment]
I also just had this same issue, thanks for the tip.

**Comment by filipewl** [comment]
One more. Please merge it. :)

**Comment by xavib** [comment]
:+1:

**Pull request merged**
