### PR TITLE
Fix outdated config in README.

### PR DESCRIPTION
**Pull request by stevejackson**
`deploy_method` causes an error, while `method` works fine.

### CODE REVIEW

**Comment by stevejackson** [comment]
Issue: https://github.com/middleman-contrib/middleman-deploy/issues/103

**Comment by kuranari-tm** [comment]
:+1:

**Comment by mtsmfm** [comment]
:+1:

**Comment by tamastimar-com** [comment]
:+1:

**Comment by stevejackson** [comment]
I'm closing this PR because the project is unmaintained - just to clear out my PR list.

**Pull request closed without merging**
