### PR TITLE
Fixing compatibility issues with middleman v4.0.0.beta.1

### PR DESCRIPTION
**Pull request by emilioforrer**
Hello, first of all thanks for this awesome gem!.

I was trying to use it with middleman v4.0.0.beta.1 and I ran into a lot of errors and issues, mostly because they changed a lot of classes, so I forked your project and fixed the errors.

There is one change that makes it incompatible with the previous versions, and it's that in the configuration options i had to rename the `method` for `deploy_method` as you can see here:

```
activate :deploy do |deploy|
  deploy.deploy_method   = :ftp
end
```

You can test it out at https://github.com/emilioforrer/middleman-deploy branch **development**

Thanks!.

### CODE REVIEW

**Comment by fny** [comment]
Any reason why this hasn't been merged yet?

**Comment by tomsabin** [comment]
Also wondering the same question, @karlfreeman?

**Comment by rriemann** [comment]
v4 support is highly appreciated. Thx @emilioforrer :+1:

**Comment by karlfreeman** [comment]
Thanks, so, so, so much @emilioforrer. This is a fantastic pull request! So good infact that I've given you read/write to this repo :+1:.

[I've cut a alpha release](https://rubygems.org/gems/middleman-deploy/versions/2.0.0.pre.alpha). It would be ace if everyone could give it a go and report "in the field" how well this fares up. In an ideal world I would have a comprehensive test suite for every deployment strategy :(.

**Comment by kirichkov** [comment]
Works for me without any issues using `rsync`

**Comment by vvo** [comment]
Can this be published as 2.0.0 non alpha now? Thanks

**Comment by munyari** [comment]
@karlfreeman are there any plans to update rubygems version to 2.0?

**Comment by andywenk** [comment]
Hi,

I just upgraded to v4 and am getting the incompatibility message. Any reason why this is not merged yet? What is the way to deploy in v4 without this fix?

Thanks and all the best

Andy

**Comment by liahsheep** [comment]
While we are waiting for the rubygem to merge, I worked around it by using this in my Gemfile:
`gem "middleman-deploy", "~> 2.0.0.pre.alpha"`

Hope it helps!

**Comment by andywenk** [comment]
Thanks @liahsheep ;-)

**Comment by barbaramartina** [comment]
Same issue here. "**_`load': Tried to activate old-style extension: deploy. They are no longer supported. (RuntimeError)_**". Thanks @liahsheep for the workaround.

**Comment by nienkedekker** [comment]
Thank you @liahsheep! Works like a charm now :)

**Pull request merged**
